### ISSUE TITLE
Usage of MPL 2.0 license with Exhibit B - "Incompatible With Secondary Licenses"

### ISSUE THREAD

**Issue by JockeJarre** [ironfede/openmcdf#100]
Is it intentional that the licence used is MPL 2.0 with Appendix B - "Incompatible With Secondary Licences" added?

As I understand it, this Appendix B makes it more complicated to combine with GPL software? 
What are your thoughts on this?

**Comment by ironfede** [comment]
Thank you @JockeJarre for your interest in OpenMcdf. 
MPL 2.0 license has no alternative formal definition with or without appendix B: the License says that if Initial Owner wants to specify that the software is released in an "incompatible way with Secondary License software she/he has to include Exhibit B to source code to specify her/his will (MPL 2.0 - 10.4).
And that's not my will so the Exhibit B ("Incompatible With Secondary Licenses" Notice) is NOT added to any of the source code files.

Best Regards,
Federico

**Comment by JockeJarre** [comment]
Thank you for confirming so quickly!
