### ISSUE TITLE
QCN MCDF  

### ISSUE THREAD

**Issue by koyuyesil** [ironfede/openmcdf#101]
Qualcomm uses the MCDF structure for NV Items backup files. I'm familiar with the structure of these streams. How can I contribute to this branch? QCNWiew official app for wiewing i want make editor. 

![QCN](https://github.com/ironfede/openmcdf/assets/730999/189793e7-5b23-44d2-b4fe-e8ef81364268)

File Version;

```
Major = br.ReadUInt16();
Minor = br.ReadUInt16();
Revision = br.ReadUInt16();
```

FeatureMask (Bit Definitons);
```

public class FeatureMask
{
public List<string> DataBits { get; set; }
public FeatureMask()
{
DataBits = new List<string>();
}

public void Read(BinaryReader br)
{
byte[] unknownByte=br.ReadBytes(2);
while (br.BaseStream.Position != br.BaseStream.Length)
{
string yourByteString = Convert.ToString(br.ReadByte(), 2).PadLeft(8, '0');
DataBits.Add(yourByteString);  
}
}
}

```
Mobile_Property_Info summary;

```
public void Read(BinaryReader br)
{
ESN= br.ReadUInt32();
MODEM= br.ReadUInt16();
MajorVersion = br.ReadByte();
MinorVersion = br.ReadByte();
ModemFirmwareVersionLength= br.ReadUInt16();//Pascal String
ModemFirmwareVersion = Encoding.ASCII.GetString(br.ReadBytes(ModemFirmwareVersionLength));
SoftwareVersionLength = br.ReadUInt16();
SoftwareVersion = Encoding.ASCII.GetString(br.ReadBytes(SoftwareVersionLength));
}

```
Nv Numbered Items
```

public class NvNumberedItem
{
public UInt16 id { get; set; }
public UInt16 index { get; set; }
public List<byte[]> data { get; set; }
public NvNumberedItem()
{
data = new List<byte[]>();
}
}
public class NvNumberedItems
{
public List<NvNumberedItem> items;
public NvNumberedItems()
{
items = new List<NvNumberedItem>();
}
public void Read(BinaryReader br)
{
while (br.BaseStream.Position != br.BaseStream.Length)
{
NvNumberedItem nvNumberedItem = new NvNumberedItem();
uint baseOffset = br.ReadUInt32();
nvNumberedItem.id = br.ReadUInt16();
nvNumberedItem.index = br.ReadUInt16();
nvNumberedItem.data.Add(br.ReadBytes(16));
nvNumberedItem.data.Add(br.ReadBytes(16));
nvNumberedItem.data.Add(br.ReadBytes(16));
nvNumberedItem.data.Add(br.ReadBytes(16));
nvNumberedItem.data.Add(br.ReadBytes(16));
nvNumberedItem.data.Add(br.ReadBytes(16));
nvNumberedItem.data.Add(br.ReadBytes(16));
nvNumberedItem.data.Add(br.ReadBytes(16));
this.items.Add(nvNumberedItem);
}
}
}

```

**Comment by ironfede** [comment]
Hi @koyuyesil , I'm not sure to have fully understood but I think you want to use OpenMcdf to create a specific editor for you use case (let me know if I'm correct).
If so you should use OpenMcdf as a dependency/base library in your project because I can't include an editor extension that is too much bound to a specific use case for a general usage library.
You should start from the Structured Storage Explorer as template and specialize it for your needs, for example.
Please, let me know If I've correctly understood your point or if I've totally missed it and you need help for something different.

Best Regards,
Federico

**Comment by koyuyesil** [comment]
Elbette! İşte talebinizin Türkçe çevirisi:

"Temel kitaplık olarak zaten çok iyi çalışıyor. Kendi özel veri yapılarına sahip ancak temel kitaplığı kullanan uygulamalar için kütüphaneyi daha esnek hale getirmek mümkün mü? Örneğin, bir Structures.DLL programladığımızda veri parçasını bu nesneye dönüştürsek nasıl çalışır? Aşağıdaki kod örneğinde olduğu gibi:

```csharp
var str = cf.RootStorage.GetStream("NV_ITEM_ARRAY");
var co = str.AsOLEPropertiesContainer();
```

Ancak `AsOleNvItemArray()` gibi bir şey olabilir mi?"

**Comment by ironfede** [comment]
@koyuyesil I think you could implement an extension/wrapper class that uses the same logic of the aforementioned example just as 
```csharp
   public static NvItemArray AsOleNvItemArray(this CFStream cfStream)
   {
       return new NvItemArray(cfStream);
   }
```

Do you see any specific issue with this approach in your Use Case?
