### ISSUE TITLE
RenameItem doesn't seem to work

### ISSUE THREAD

**Issue by Ferroreson** [ironfede/openmcdf#116]
I'm attempting to rename a CFStorage within a CFStorage.  The root CFStorage is called "Relays".  Within Relays is one CFStorage that I'm attempting to rename.  

I pass in the Compound File as an array of bytes to ReadFileBytes, then call the RenameSettingFileEntry, then call GetRDBFileData() and write the byte array to a file.  The "RenameItem" function runs without error but doesn't rename the CFStorage.  Thanks for your help!

        private string DeviceRootPath = "Relays";
        private MemoryStream rdbMemoryStream;
        private CompoundFile rdbCompoundFile;

        private void ReadFileBytes(byte[] fileData)
        {
            rdbMemoryStream = new MemoryStream(fileData);  
            if (rdbCompoundFile != null)
            {
                rdbCompoundFile.Close();
                rdbCompoundFile = null;
            }
            rdbCompoundFile = new CompoundFile(rdbMemoryStream, CFSUpdateMode.ReadOnly, CFSConfiguration.Default);
        }
        public void RenameSettingFileEntry(string OldName, string NewName)
        {
            var DeviceRootEntry = (CFStorage)rdbCompoundFile.GetAllNamedEntries(DeviceRootPath).First();
            DeviceRootEntry.RenameItem(OldName, NewName);
        }
        public byte[] GetRDBFileData()
        {
            MemoryStream s = new MemoryStream();
            rdbCompoundFile.Save(s);

            return s.ToArray();
        }

**Comment by Ferroreson** [comment]
Bug isn't with OpenMCDF.

**Comment by ironfede** [comment]
This should work.
You can change a storage from its parent storage.

```c#
CompoundFile cf = new CompoundFile();
cf.RootStorage.AddStorage("AStorage")
    .AddStream("AStream")
    .SetData(Helpers.GetBuffer(100));

cf.SaveAs("Hello$File");
cf.Close();

CompoundFile cf1 = new CompoundFile("Hello$File", CFSUpdateMode.Update, CFSConfiguration.Default);
try
{
    cf1.RootStorage.RenameItem("AStorage", "NewStorage");
    cf1.Commit();
    cf1.Close();
}
catch (Exception ex)
{
   Assert.Fail(ex.Message);
}
```

Kind Regards,
Federico

**Comment by Ferroreson** [comment]
Thank you!!
