### ISSUE TITLE
Work incorrect with '.automaticDestinations-ms'

### ISSUE THREAD

**Issue by shanxing2** [ironfede/openmcdf#127]
Hi,i use **openmcdf** to modify '.automaticDestinations-ms' file in C:\Users\username\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations.I want to modify the username in the file, but I have encountered some issues.
If i modify it use same length data it work good but not same length work incorrect.After modify,if the data length is the same,both **StructuredStorageXplorer 2.3.1.0** and **JumpListExplorer V2.0.0.0** can be read normally.However, if the data length is different, **StructuredStorageXplorer** can read it normally, but **JumpListExplorer** cannot read it properly, and the Windows system cannot recognize this file properly.

![00](https://github.com/ironfede/openmcdf/assets/12883135/b97ddc42-0429-41e5-ad62-31690bda6d51)
![01](https://github.com/ironfede/openmcdf/assets/12883135/b677e454-20ef-4f00-945f-a688173c1411)

for example,file 'f01b4d95cf55d32a.automaticDestinations-ms',username is 'pty',i replace it to 'abc',it work good.However,if i replace it to 'abchhh',**StructuredStorageXplorer** and the Windows system cannot recognize this file properly.
The error prompted by a is ‘**Offest and length were out of bounds for the arrya or count is greater than the number of elements from index to the end of the source collection.**’

Here is my code in vb.net.

```c#
Dim action = Sub(target As CFItem)
                         Debug.Print($"entry {target.Name}（{If(target.IsStream, target.Size & " bytes", "")}）")
                         Dim cfstream  = TryCast(target, CFStream)
                         Dim oldBytes = cfstream.GetData
                         Dim newBytes= some code to replace 'pty' to 'pty233' in oldBytes
                         cfstream.SetData(newBytes)
                     End Sub

Using fs = New FileStream(file, FileMode.Open, FileAccess.ReadWrite, FileShare.Read)
    Using cf = New CompoundFile(fs, CFSUpdateMode.Update, CFSConfiguration.Default)       
        cf.RootStorage.VisitEntries(action, False)

        cf.Commit(True)
    End Using
```

**Comment by ironfede** [comment]
Hi @shanxing2 , what happens (only for test) if you change data in a single entry and not in a loop for all entries?  I would understand if issue is action-loop related or if there's some problem in the single write/commit operation. Thank you

**Comment by shanxing2** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的邮件，看到之后会尽快给您回复。

**Comment by shanxing2** [comment]
Yes, I have tested it and there are also issues when changing only a single entry.

**Comment by shanxing2** [comment]
Yes, I have tested it and there are also issues when changing only a single entry.

**Comment by shanxing2** [comment]
I found that the length did not change after the modification.
![image](https://github.com/ironfede/openmcdf/assets/12883135/0d6cf171-fe49-4d83-b667-9f8c23a63935)
