### ISSUE TITLE
How to know the size of a Compound file?

### ISSUE THREAD

**Issue by alanccw** [ironfede/openmcdf#129]
Hi,

Is there a way to know the size of a compound file via its header?

Or, alternative, get the total number of sectors, including the FAT sectors, dir sectors and user data sectors, from the header in the compound file?

**Comment by Numpsy** [comment]
The numbers of sectors are stored in the header - ref https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-cfb/05060311-bfce-4b12-874d-71fd4ce63aea - I haven't looked at this part in much detail though.

**Comment by alanccw** [comment]
@Numpsy 

No, in your link, there are:

1. Number of Directory Sectors
2. Number of FAT Sectors
3. Number of Mini FAT Sectors
4. Number of DIFAT Sectors

But the most important number, the number of normal data sectors are missing. So I cannot calculate the total number of sectors in the file

**Comment by jeremy-visionaid** [comment]
@alanccw The number of utilized sectors are only know by consulting the FAT (i.e. it's beyond the data available directly from the header). AFAIK, the entire FAT would need to be enumerated to find out how many sectors were free or in use.
