### ISSUE TITLE
Unit Test Coverage

### ISSUE THREAD

**Issue by ArminFirecracker** [ironfede/openmcdf#17]
We at http://www.brainproducts.com/ thinking of using OpenMcdf for our next project. So I had a deeper look into the functionality and I'm quite happy!

There are some parts of the code not covered by the unit test. I wonder if you are aware of that. 

Like this method:

`public CompoundFile(Stream stream, CFSUpdateMode updateMode, CFSConfiguration configParameters)`

**Comment by jeremy-visionaid** [comment]
@ArminFirecracker as part of #194 I've been looking to extend the test coverage. Coverlet currently shows about 80% coverage of the core library. I'd like to get to the point where at least all the public methods are invoked by unit tests, at which point I'd consider this closed.

**Comment by jeremy-visionaid** [comment]
Unit test coverage is now at ~90% and covers the full public API surface for v3.0. Most of the remaining code is for interface implementations that happen to be unused and a few corner cases for corrupt data structures. Eventually it would be nice to have tests for the corrupt data strucutres, but I think enough has been done to close this ticket now.
