### ISSUE TITLE
.net standard support

### ISSUE THREAD

**Issue by michaelp** [ironfede/openmcdf#19]
Based on API compatibility analysis,  openmcdf is 100% .net standard capable 
[openmcdf_report.zip](https://github.com/ironfede/openmcdf/files/2013640/openmcdf_report.zip)

It would be valuable to have openmcdf multi-targeting .net framework and .net standard

**Comment by michaelp** [comment]
@ironfede, any objections/comments if I try to do the port?

**Comment by ironfede** [comment]
No objection :-)! Thank you for your interest in openmcdf. If you want, you can open a pull request in order to merge changes in main branch when finished.

**Comment by michaelp** [comment]
Just an update: I have an issue with two tests that fail with the out of memory exception. The tests try to create multi gigabyte streams. Other than that, no obvious issues. I was busy for the last two weeks But i hope to resolve the issue during the next week.

**Comment by SimonCropp** [comment]
@michaelp can u share your work by submitting a PR?

**Comment by michaelp** [comment]
Already shared , what is missing is only tests. @SimonCropp . (actually only two tests are problematic)

**Comment by michaelp** [comment]
@ironfede @SimonCropp https://github.com/michaelp/openmcdf/commits/netsdt
everything pushed. The problem is in the two tests that are trying to create large streams (6gb are accumulated in memory ) In general, there are changes required to reduce internal memory allocations.

**Comment by michaelp** [comment]
@ironfede @SimonCropp 
Heads up: I am reviewing the work that @ata6502 did on my fork in order to resolve all the issues. The claim is that everything is resolved. Once, I have the evidence that everything looks good, let's proceed. ETA - today (July 6th)

**Comment by michaelp** [comment]
@ironfede , @SimonCropp @altso
I tend to think that the support for .net standard is ready. I run the tests locally and they are passing without issues. In general, changes to the code were minimal, the change was mainly in the projects formats. Please notice that `dotnet pack` generates multi-targeting packages as would be expected. The behavior of `dotnet test` as also standard. **A major thing to remember is to pay attention to the package versions since they are deterministic now** (i.e. require manual care)   @ata6502 run the packages on our private code base and no obvious issues were found. I do observe that performance wise openMCDF is challenged in comparison to the COM driver when it comes to our scenarios. I profiled it and it seems to be a problem of constant resizing of collections and general memory management. But this is a topic for another pull request. 

Please review and merge this pull request

**Comment by altso** [comment]
@ironfede, @michaelp thanks for you work on .net standard support. When do you plan to release this version on nuget?

**Comment by ironfede** [comment]
@altso I hope to have time to create and publish ngpack during this weekend.

**Comment by SimonCropp** [comment]
awesome work everyone :) thanks
