### ISSUE TITLE
[memory management] Investigate possible usage of arena allocation technique in internals of openMCDF libaray

### ISSUE THREAD

**Issue by michaelp** [ironfede/openmcdf#27]
The task boils down to the investigation of the possible usage of the following friends
MemoryPool<T>, IMemoryOwner<T>, MemoryManager<T> ,ArrayPool<T> , Memory<T>, BufferManager in the internal allocations of the openMCDF.  Unlike issue #26 , this task is intended to tackle the problem without introducing breaking API changes.

**Comment by michaelp** [comment]
@ironfede i am starting with this one, if you don't mind. Is there anything that I should know?

**Comment by jeremy-visionaid** [comment]
@michaelp The memory usage has been significantly reduced as part of #194 by utilizing enumerators instead of lists. For the most part it doesn't generally use pools (aside from a few cases to provide modern equivalents of ReadExactly for old TFMs i.e. netstandard2.0)

**Comment by jeremy-visionaid** [comment]
I'm hopeful that 3.0.0-preview1 should get released to NuGet in the next few days. @ironfede has kindly granted me write access to the repo, so I'll go ahead and close this one as fixed by #194.
