### ISSUE TITLE
Unrecognized property type

### ISSUE THREAD

**Issue by nullldata** [ironfede/openmcdf#32]
Hi Ironfede,

We have been using your library in a project at work where I am grabbing the "Creation Date" property from old format office files that contain it (doc, xls, ppt, for example - pub and vsd files don't seem to have the property).

We found that it works really well, but some files throw an "Unrecognized property type" exception. 
We can't figure out why.

When we check the files with "SSView", we can see the date exists. 
Similarly, the date exists within the Windows File Explorer properties.

Our test code is simple:

```
using System;
using OpenMcdf;
using OpenMcdf.Extensions;
using OpenMcdf.Extensions.OLEProperties;
using OpenMcdf.Extensions.OLEProperties.Interfaces;

namespace ConsoleApp4
{
    class Program
    {
        static void Main(string[] args)
        {
            string file = @"c:\temp\_Test2.doc";

            CompoundFile cf;

            try
            {
                cf = new CompoundFile(file);
            }
            catch (CFFileFormatException cfe)
            {
                Console.WriteLine(file + " isn't a valid OLE Storage file. " + cfe.Message);
                Console.ReadKey();
                return;
            }

            int numDirectories = cf.GetNumDirectories();

            for (int i = 0; i < numDirectories; i++)
            {
                Console.WriteLine(cf.GetNameDirEntry(i));
            }

            CFStream stream = cf.RootStorage.GetStream("\u0005SummaryInformation");

            PropertySetStream ps = CFStreamExtension.AsOLEProperties(stream);

            int count = 0;

            foreach (PropertyIdentifierAndOffset propId in ps.PropertySet0.PropertyIdentifierAndOffsets)
            {
                Console.WriteLine(count + ": " + propId.PropertyIdentifier.GetDescription());
                count++;
            };

            count = 0;

            foreach(ITypedPropertyValue prop in ps.PropertySet0.Properties)
            {
                Console.WriteLine(count + ": " + prop.GetType() + ": " + prop.PropertyValue);
                count++;
            }
            Console.ReadKey();
        }
    }
}
```

The issue is thrown on the following line:

`PropertySetStream ps = CFStreamExtension.AsOLEProperties(stream);`

We can't figure out whether the issue is with the file, our code, or the library...

In 1 case, a file that was not working suddenly started working after we changed some document properties (removed author). Weird.
Attempting to do this on another file had no effect.

Attempting to find the original age of a document will help us with our document retention automation in SharePoint.  This isn't our SharePoint code, it's just a console app to test pulling back the values from the stream.
With GDPR being a thing nowadays, handling all these old files is suddenly also a thing too.

Can you help please?

Thanks for your excellent work!

**Comment by ironfede** [comment]
I've added some enhancement in OLE Properties handling that hopefully should allow DocumentSummaryInfo and SummaryInfo sets parsing. Please, consider OLE properties still in a _beta_ stage because not all property types are supported and this feature needs a deep unit testing to be considered really a production-ready feature nevertheless it's a useful extension so please let me know if there are other issues possibly attaching an example file to analyze.
Best Regards,
Federico

**Comment by ironfede** [comment]
Extension package 2.2.1.3 published.

**Comment by nullldata** [comment]
Thank you so much Federico, I'll go and get the new package now and test :)

Much appreciated!

**Comment by nullldata** [comment]
Hi Federico,

Unfortunately, this did not fix our issue.

I have attached a .ppt file (in a zip) that contains a date, but cannot seemingly be grabbed by OpenMCDF.

Some properties seem to have changed in this new version:

"PropertyValue" is now "Value", for example.

![image](https://user-images.githubusercontent.com/42836083/48939123-289f3000-ef0b-11e8-926c-4d04bc27e985.png)

![image](https://user-images.githubusercontent.com/42836083/48939187-571d0b00-ef0b-11e8-9086-caba7c62892f.png)

[_Test.zip](https://github.com/ironfede/openmcdf/files/2610377/_Test.zip)

**Comment by ironfede** [comment]
Thank you for this test-case. I've found the issue (missing clipboarddata property type) and it will be fixed as soon as possible. 
Please, take in account that api is not stable yet so expect some required changes due to refactoring.

**Comment by nullldata** [comment]
Hi Federico,

Thanks for looking at it again. I appreciate your efforts very much.

**Comment by ironfede** [comment]
Please, take a look at current codebase (no nuget yet) to see if this partial commit fix reported issue. 
API is being refactored (OLE properties sub-project) so some client code change could probably be required.

**Comment by ironfede** [comment]
Hi, 
please @Numpsy , attach file because I'll use those samples in unit test if it's ok for you.
I'm progressively adding property types and I'm trying to cover all MS-OLEPS specifications.
Milestone is 2.3.0.0 for OpenMcdf extensions.

**Comment by Numpsy** [comment]
This file has Author and Keywords properties of type LPWSTR.

[wstr_presets.zip](https://github.com/ironfede/openmcdf/files/2621974/wstr_presets.zip)

**Comment by ironfede** [comment]
LPWSTR support added.
Work in progress...

**Comment by ironfede** [comment]
Please, take in account that OLEProperties Container still does not support write methods (NotImpementedException to avoid issues)

**Comment by ironfede** [comment]
@Numpsy please, let me know if current code base close this issue.
Thank you!

**Comment by ironfede** [comment]
Thanks @Numpsy. Yes, ole strings have null termination AND a size field so I think that it's better if client application applies a post filter to handle them in its preferred way at the moment. I will introduce some type of configuration parameter to specify how handle null characters.

**Comment by nullldata** [comment]
Seems like this is a thread hijack to me! 

Can I ask why this bug report has been closed?

**Comment by ironfede** [comment]
Sorry, but i thought that last report  means "ok". If you think it's not i
will reopen.

Il giorno ven 7 dic 2018, 15:39 nullldata <notifications@github.com> ha
scritto:

**Comment by nullldata** [comment]
We are currently trying to compile from source, however it's not yet compiling. Looking into it.
Previously, we used Nuget to add the extension.

From our perspective, we don't have a working solution currently.

Will update when we successfully compile and test.

Sorry for slow reply, I've been away.

**Comment by ironfede** [comment]
@nullldata , i'm going to close issue.
Please let me know if it's ok.
Nuget package will be released when OLE properties read/write project will be closed as "Production ready". So I think that it will take some time to reach 2.3.0.0 milestone... stay tuned ;-)
Thank you for your reports and for your patience.

**Comment by nullldata** [comment]
@ironfede Sure, no problem.

Thanks again! :)
