### ISSUE TITLE
System.ArgumentOutOfRangeException when trying to open certain invalid files

### ISSUE THREAD

**Issue by Numpsy** [ironfede/openmcdf#38]
Hi,
Not sure what the official situation is with exception types, but for what it's worth, both of the files in the attached [ArgumentOutOfRangeException.zip](https://github.com/ironfede/openmcdf/files/2738597/ArgumentOutOfRangeException.zip) cause a System.ArgumentOutOfRangeException to be thrown if you try to load them with OpenMCDF, was wondering if that should really be a CFCorruptedFileException or CFException or some such?

**Comment by ironfede** [comment]
Fixed in current main branch. 
Added CFCorruptedException and CFException wrappers for uploaded cases.
Thank you @Numpsy
