### ISSUE TITLE
Trend Micro is quarantining OpenMcdf.dll

### ISSUE THREAD

**Issue by wkinnett** [ironfede/openmcdf#49]
Has anyone else had there dll deleted by antivirus?  We started getting tagged for this dll because it was used by a malware product, evilclippy (https://kalilinuxtutorials.com/evilclippy-malicious-ms-office-documents/).

Guilt by association I suppose!

**Comment by Warlock78** [comment]
[https://www.virustotal.com/gui/file/ba9755cc15501ee7a9637f0e3e0c8ea2b5916c4f1d94e0312d41a10e2d79ddc8/detection](url)

**Comment by ironfede** [comment]
I've sent a note to Trend Micro using their re-classification form at https://www.trendmicro.com/en_us/about/legal/detection-reevaluation.html
If you think it can be useful, please send a note you too. 
This misclassification is really annoying imho...
Thank you, Federico

**Comment by dhaas84** [comment]
Same problem here. I've also sent a re-evaluation request to Trend Micro.

**Comment by ironfede** [comment]
Thank you! And many thanks to all people asking Trend Micro for re-classification: I hope that they'll recognize this mistake.

**Comment by ironfede** [comment]
Closing with the hope that this type of false-positive virus responses will not present again in the future.
