### ISSUE TITLE
Fuzzed test data causes hang in the library

### ISSUE THREAD

**Issue by AmeetShinde** [ironfede/openmcdf#50]
We were testing the library from security perspective using fuzzed data, and in some cases the library hangs if we modify header structures. Please find attached the culprit file

[64-67(numberOfMiniFATSectors).docx](https://github.com/ironfede/openmcdf/files/3191126/64-67.numberOfMiniFATSectors.docx)

Is there any way to validate header structures for valid values?

**Comment by ironfede** [comment]
Thank you @AmeetShinde for your report.
Your attached file seems not to be a valid compound file and this is correctly recognized by OpenMcdf -> CFFileFormatException("Invalid OLE structured storage file");
Do you have another file to test for?
I'm closing this issue: if you think this is wrong, please open a new issue with anoter fuzzed file, valid from a specifications point of view.
Many thanks,
Federico
