### ISSUE TITLE
Find out Stream Name

### ISSUE THREAD

**Issue by prabhakaran2014** [ironfede/openmcdf#61]
Hi,
How to find out storage(CFStorage) Stream Name?
I can able to check stream name with condtion by storage.TryGetStream("CONTENTS") .
But I need to get the Stream name from CFStorage object

**Comment by jeremy-visionaid** [comment]
I'm hopeful that 3.0.0-preview1 should get released to NuGet in the next few days. @ironfede has kindly granted me write access to the repo, so I'll go ahead and close this one as fixed by #194.
