### ISSUE TITLE
Is there a way to get a list of all streams and storages inside a compound file?

### ISSUE THREAD

**Issue by MOSAMAEgypt** [ironfede/openmcdf#63]
Is there a way to get a list of all streams and storages inside a compound file? List items would be like 'Storage1\Storage2\Storage3\Stream"

**Comment by ironfede** [comment]
Hi @MOSAMAEgypt ,
currently you can use the method of CFStorage named VisitEntries(...) starting on root storage, in a recursive way, using the action parameter to list all contained items.
Best Regards,
Federico
