### ISSUE TITLE
Wrong AssemblyVersion

### ISSUE THREAD

**Issue by Markus-Dressel** [ironfede/openmcdf#70]
AssemblyVersion is 2.2.1.**5** for version 2.2.1.**6** and that's causing issues when the package is installed as a dependency of another package via NuGet (MsgReader for example)

**Comment by ironfede** [comment]
Fixed. Republishing new version. Thank you.
Best Regards,
Federico

**Comment by Markus-Dressel** [comment]
Thanks!
