### ISSUE TITLE
Source array was not long enough

### ISSUE THREAD

**Issue by wf-soft** [ironfede/openmcdf#77]
@ironfede Hi! ironfede.

I encountered a getdata() exception reading from the stream.

`
CFStream stream = compoundFile.RootStorage.GetStream(DocumentSummaryInformation.DEFAULT_STREAM_NAME);
PropertySet ps = new PropertySet(stream.GetData());  <-----
`

One or more errors occurred. (Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray'))

**Comment by Numpsy** [comment]
I don't think anything can be done for this without either more information or a test file that shows the error?

**Comment by ironfede** [comment]
Yes I agree. I kindly ask @wf-soft if he/she can provide a test file for the error.
Many thanks,
Federico

**Comment by ironfede** [comment]
@wf-soft , I have to close this issue in absence of a test file as not reproducible.
Please create a new issue if you have a test file to check for.
Thank you.
