### ISSUE TITLE
Official Website Still Refering SourceForge as Master-Copy

### ISSUE THREAD

**Issue by bormm** [ironfede/openmcdf#8]
@ironfede  

Hi Federico! 
I sent some notification to some of the sourceforge forks on github, that the original is now on github and forking not needed anymore.
I have seen that http://openmcdf.sourceforge.net/ seams still the "official website" of your project -> It is the first hit on google and also linked on the nuget page.
This site also still links to the sourceforge page as reference for the project and the source code. Also the sourceforge bugtracker is still active and so still used.

You can also use github pages to host the project website as part of the repo:
https://pages.github.com/

Just some note from me about for that. ;-) Maybe you missed that.
Have a nice day!

**Comment by ironfede** [comment]
Thank you Marco,
I'm going to clean up things with website and trackers in the next two weeks.
Kind Regards,
Federico
