### ISSUE TITLE
Error reading the data

### ISSUE THREAD

**Issue by steffi3011** [ironfede/openmcdf#80]
There is an error in the "ReadData(...)" method when reading the data. The variable count is set incorrectly.

**Comment by ironfede** [comment]
Thank you @steffi3011  
Please take a look at https://github.com/ironfede/openmcdf/pull/81#pullrequestreview-586005251 for some explanation about the closure of this issue.
Please, let me kindly know if you think that solution is not effective or if you have any doubt.
Best Regards,
Federico
