### ISSUE TITLE
'Potential' issue with Delete

### ISSUE THREAD

**Issue by mmattner** [ironfede/openmcdf#96]
I have been trying to make use of MCDF to write some code to be able to extract entries from a third party compound file (generated by Visual Pinball) individually to 'back them up'. 

the backup / restore process would require the abiltiy to take a compound file and be able to copy out individual storage elements from root storage, delete them, and to be able to reinsert them later if needed.

I have found that once I start writing to the file I occasionally get cases where corrupt file errors are thrown,. Ive been trying to track down and as such have written a test harness to demonstrate the problem. 

In this case the harness runs through the compound file, and one by one extracts the root storage elements to their own files, and then tries to loop through the original file and delete each element in turn ... which should result in an empty file. I seem to get a heap of 'Value must be non-negative and less than or equal to Int32.MaxValue. (Parameter 'srcOffset')' errors being thrown.

I cannot confirm that the original file is valid however a third party tool "SSViewer" (https://www.mitec.cz/ssv.html) seems to have no issues reading/deleting these entries.

I have been told its a Compound file and reading it cleanly suggests htat is the case.

I have attached  azip with the example source code I used to demonstrate the problem, plus the sample file I used to test.
[TestDeletes.zip](https://github.com/ironfede/openmcdf/files/11270894/TestDeletes.zip)

**Comment by ironfede** [comment]
First of all many thanks @mmattner  for your test program.
I think I've found the issue ant it comes from a combination of a weak check of "Update Mode" in OpenMcdf and from the particular combination of savings in your test that allowed me to recognize this problem.
If you modify the delete portion according to:

        `Console.WriteLine("Delete {0} entries via loop", FILENAME);
        List<string> entriesToDelete = GetEntries(FILENAME);
        //Open file ONE TIME:
            CompoundFile cf = new CompoundFile(FILENAME);
            
            foreach (string entryName in GetEntries(FILENAME))
            {
                cf.RootStorage.VisitEntries(i =>
                    {
                        if (i.Name == entryName)
                        {
                            try
                            {
                                cf.RootStorage.Delete(entryName);
                                Console.WriteLine("Deleted entry {0} from {1}", entryName, FILENAME);
                            }catch(Exception ex)
                            {
                                Console.WriteLine("An error occured: filename={0}, entry={1}, error={2}", FILENAME, entryName, ex.Message);

                            }
                        }
                    }, false);

                //DeleteEntry(entryName);
            }

            cf.Save(FILENAME + "_DELETED");
            cf.Close();`

...it should work as expected and can be considered the correct way to save (with name) a ReadOnly opened file.

**The restore part should follow the same pattern:** open file, operate in memory, finally one single save as.

Otherwise you can open file in UpdateMode and do partial commits

The problem arise when you open, delete entry and save a Read-Only Compound file.
This action **should NOT be allowed** and an exception should be raised informing you CAN'T reopening the same file and overwrite the backend filestream of an already loaded image.

Obviously this check is not performed correctly by the library and THIS is the bug to close asap.

The fix could potentially impact existing implementations but I prefer to avoid file corruptions.

I hope this can help in your implementation and please stay tuned for a fix of this problem.

Thank You.

Best Regards,
Federico

**Comment by mmattner** [comment]
Thanks Federico.

I will take a look at your changes tonight and confirm it works.
I did stumble across another option that aseemed to work with a change to the Restore method. 
I had retried running my test and saw it worked the first time, but if I reinjected the file I had created as the starting point of the second test it failed.... so I experimented with adding a commit in the restore method. 

So I made a change to my Restore method and put the code in the Main function into a loop and was able to run hundreds of times with the ouytput of the first run being used as input for the second ... and so forth. I should point out in that test I had also replaced the delete method you can see with one that created a new "backup" file and added all the entires other than the one I wanted to delete. So I should be able to swap that out for your version I suspect.

I'll report back how I go

**Comment by mmattner** [comment]
One point you made was: "This action should NOT be allowed and an exception should be raised informing you CAN'T reopening the same file and overwrite the backend filestream of an already loaded image."
Is there a way to clear the 'already loaded image'. IE open a file, make a change, close it and unload the image, so that you are in the same state as you werebefore the original open ?


While my test program uses loops to backup, delete, and restore entries from the Compound File, this was done for test purposes only to demonstrate.

My real use case would be a user at different times via a GUI deciding to backup one or more individual entries from the file (Ie calling Backup entry), and then at some point later electing to delete entries (via DeleteEntry). They may then decide they want to recover the deleted entries so would restore them (via RestoreEntry).


I have attached an updated version of my test script. Please note that I strongly suspect that the original VPReg.stg file I sent you had been corrupted already by me trying to get this working, and hence may not be recoverable ..... I tried running your delete method over it and it failed still... but I sort of expected that if I have corrupted the file it may not work ? (although I guess SSview did work on it.

This updated version has a new version of the **DeleteEntry** method called **DeleteEntryCommit** which is currently being called, as well as a similar update to the Restore. (basically I replaced the save with commit calls, and opened the files in update mode.

I have commented out the original **DeleteEntry** method. Also included is a thirds delete method, called **DeleteEntryAlternate** which I had tried as an alternate. This method also worked - Im guessing because it was writing the entries to a new Compound file, and didnt need the updatecommit flags. 

Assuming I am correct, my final solution will use the **DeleteEntryCommit** and **RestoreEntry** changes I have applied and remove the other versions.
Yuo will see the main function is looping over the file 10 times to show that the file I restore has the same content as the original file and helps me feel comfortable.
Line 7/8 of the test file lets you flick between the new test file (which wasnt previously corrupted by me) as well as the old file you saw in the first test that I beleive is corrupt.

**Comment by ironfede** [comment]
I think that committing is the correct way to work in your use case. Issue is contained in Save() method: it simply shoudn't allow you to save a file while in ReadOnly Mode overwriting it. I will fix it and it should rise an exception if trying to save to the same filestream. Please, Let me know if this scenario is recognizable as "correct" for you.
Many Thanks
Federico

**Comment by mmattner** [comment]
This all looks good to me

**Comment by ironfede** [comment]
Fixed and test added
